TOOLS_DB = [
    {
        "id": "merge",
        "name": "PDF Merge",
        "description": "Combine multiple PDF files into one. Drag to reorder.",
        "icon": "merge",
        "route": "/tools/merge",
        "category": "Basic Tools",
        "max_files": 20,
        "max_size_mb": 100,
        "max_total_size_mb": 200,
        "options": [
            {
                "name": "output_filename",
                "type": "string",
                "label": "Output Filename",
                "default": "merged.pdf",
                "required": False,
            }
        ],
    },
    {
        "id": "split",
        "name": "PDF Split",
        "description": "Split a PDF file into multiple files",
        "icon": "scissors",
        "route": "/tools/split",
        "category": "Basic Tools",
        "max_files": 1,
        "max_size_mb": 100,
        "max_total_size_mb": 100,
        "options": [
            {
                "name": "mode",
                "type": "select",
                "label": "Split Mode",
                "options": [
                    {"value": "range", "label": "Extract Pages by Range"},
                    {"value": "every", "label": "Split Every N Pages"},
                    {"value": "single", "label": "Split into Single Pages"},
                ],
                "default": "range",
            },
            {
                "name": "ranges",
                "type": "string",
                "label": "Page Ranges",
                "description": "Enter page ranges (e.g., 1-3, 5-7). Use -1 for last page.",
                "placeholder": "1-3, 5-7, 9-10",
                "depends_on": {"mode": "range"},
                "required_when": {"mode": "range"},
            },
            {
                "name": "every_n",
                "type": "number",
                "label": "Pages per File",
                "description": "Split the PDF every N pages",
                "min": 1,
                "max": 100,
                "default": 2,
                "depends_on": {"mode": "every"},
                "required_when": {"mode": "every"},
            },
        ],
    },
    {
        "id": "extract_pages",
        "name": "Extract Pages",
        "description": "Extract specific pages from PDF to create a new file",
        "icon": "file-text",
        "route": "/tools/extract-pages",
        "category": "Extract Tools",
        "max_files": 1,
        "max_size_mb": 100,
        "max_total_size_mb": 100,
        "options": [
            {
                "name": "pages",
                "type": "string",
                "label": "Pages",
                "description": "e.g., 1,3,5-7,9",
                "placeholder": "1,3,5-7,9",
                "required": True,
            }
        ],
    },
    {
        "id": "extract_text",
        "name": "Extract Text",
        "description": "Extract text content from PDF files",
        "icon": "type",
        "route": "/tools/extract-text",
        "category": "Extract Tools",
        "max_files": 1,
        "max_size_mb": 50,
        "max_total_size_mb": 50,
        "options": [
            {
                "name": "format",
                "type": "select",
                "label": "Output Format",
                "options": [
                    {"value": "txt", "label": "Plain Text (.txt)"},
                    {"value": "json", "label": "JSON (.json)"},
                ],
                "default": "txt",
            }
        ],
    },
    {
        "id": "add_watermark",
        "name": "Add Watermark",
        "description": "Add text or image watermark to PDF",
        "icon": "droplet",
        "route": "/tools/add-watermark",
        "category": "Watermark Tools",
        "max_files": 1,
        "max_size_mb": 100,
        "max_total_size_mb": 100,
        "options": [
            {
                "name": "type",
                "type": "select",
                "label": "Watermark Type",
                "options": [
                    {"value": "text", "label": "Text Watermark"},
                    {"value": "image", "label": "Image Watermark"},
                ],
                "default": "text",
            },
            {
                "name": "text",
                "type": "string",
                "label": "Watermark Text",
                "placeholder": "Enter watermark text",
                "required": False,
            },
            {
                "name": "opacity",
                "type": "number",
                "label": "Opacity",
                "min": 0,
                "max": 100,
                "default": 30,
            },
            {
                "name": "rotation",
                "type": "number",
                "label": "Rotation Angle",
                "description": "Any angle from 0 to 360 degrees is supported",
                "min": 0,
                "max": 360,
                "default": 45,
            },
        ],
    },
    {
        "id": "pdf_to_images",
        "name": "PDF to Images",
        "description": "Convert PDF pages to images",
        "icon": "image",
        "route": "/tools/pdf-to-images",
        "category": "Convert Tools",
        "max_files": 1,
        "max_size_mb": 100,
        "max_total_size_mb": 100,
        "options": [
            {
                "name": "mode",
                "type": "select",
                "label": "Page Selection",
                "options": [
                    {"value": "all", "label": "All Pages"},
                    {"value": "range", "label": "Page Range"},
                    {"value": "single", "label": "Single Page"},
                ],
                "default": "all",
            },
            {
                "name": "ranges",
                "type": "string",
                "label": "Page Ranges",
                "description": "Enter page ranges (e.g., 1-3, 5-7)",
                "placeholder": "1-3, 5-7",
                "depends_on": {"mode": "range"},
                "required_when": {"mode": "range"},
            },
            {
                "name": "page",
                "type": "number",
                "label": "Page Number",
                "description": "Single page to convert",
                "min": 1,
                "max": 10000,
                "default": 1,
                "depends_on": {"mode": "single"},
                "required_when": {"mode": "single"},
            },
            {
                "name": "format",
                "type": "select",
                "label": "Output Format",
                "options": [
                    {"value": "png", "label": "PNG"},
                    {"value": "jpg", "label": "JPG"},
                    {"value": "webp", "label": "WebP"},
                ],
                "default": "png",
            },
            {
                "name": "dpi",
                "type": "select",
                "label": "Resolution",
                "options": [
                    {"value": "72", "label": "72 DPI (Screen)"},
                    {"value": "150", "label": "150 DPI (HD)"},
                    {"value": "300", "label": "300 DPI (Print)"},
                ],
                "default": "150",
            },
        ],
    },
    {
        "id": "encrypt_decrypt",
        "name": "Encrypt / Decrypt",
        "description": "Add or remove password protection from PDF files",
        "icon": "lock",
        "route": "/tools/encrypt-decrypt",
        "category": "Security Tools",
        "max_files": 1,
        "max_size_mb": 100,
        "max_total_size_mb": 100,
        "options": [
            {
                "name": "operation",
                "type": "select",
                "label": "Operation",
                "options": [
                    {"value": "encrypt", "label": "Encrypt (Add Password)"},
                    {"value": "decrypt", "label": "Decrypt (Remove Password)"},
                ],
                "default": "encrypt",
            },
            {
                "name": "password",
                "type": "string",
                "label": "Password",
                "description": "Enter password for encryption or decryption",
                "placeholder": "Enter password",
                "required": True,
            },
            {
                "name": "algorithm",
                "type": "select",
                "label": "Encryption Algorithm",
                "description": "Choose encryption strength (higher is more secure)",
                "options": [
                    {"value": "AES-256", "label": "AES-256 (Recommended)"},
                    {"value": "AES-128", "label": "AES-128"},
                    {"value": "RC4-128", "label": "RC4-128"},
                    {"value": "RC4-40", "label": "RC4-40 (Legacy)"},
                ],
                "default": "AES-256",
                "depends_on": {"operation": "encrypt"},
            },
            {
                "name": "allow_printing",
                "type": "boolean",
                "label": "Allow Printing",
                "description": "Allow users to print the PDF",
                "default": True,
                "depends_on": {"operation": "encrypt"},
            },
            {
                "name": "allow_copying",
                "type": "boolean",
                "label": "Allow Copying",
                "description": "Allow users to copy text and images",
                "default": True,
                "depends_on": {"operation": "encrypt"},
            },
            {
                "name": "allow_modifying",
                "type": "boolean",
                "label": "Allow Modifying",
                "description": "Allow users to modify the PDF",
                "default": True,
                "depends_on": {"operation": "encrypt"},
            },
        ],
    },
]
